# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pmolokwa <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/26 13:30:24 by pmolokwa          #+#    #+#              #
#    Updated: 2020/01/26 13:59:15 by pmolokwa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CFILES = *.c
OBJ = *.o
COMPILER = gcc -c $(CFILES)  

all: $(Name)
	$(COMPILER)

clean: 
	/bin/rm -f $(OBJ)
fclean:
	/bin/rm -f $(NAME)

re: fclean all
